dist: xenial
sudo: required
services:
- docker
branches:
  only:
  - travis-ci
cache:
  ccache: true
  pip: true
  directories:
    - dpdk
    - node_modules
language:
- c
- python

before_install:
- chmod +x install-apt.sh
- tr -d '\r' < install-apt.sh > install-apt-r.sh
- chmod +x install-apt-r.sh
- chmod +x install-test.sh
- docker build . --tag 16.04-travis
- docker run -d -v `pwd`:/CI-test 16.04-travis --name travis-cont
- docker exec -it travis-cont /bin/sh -c "./install-apt-r.sh; PATH=/opt/gcc-arm/bin:$PATH"
- docker ps -a
- docker exec -it 16.04-travis /bin/sh -c "./install-test.sh"
install:
- pwd
matrix:
  fast_finish: true
  if: branch = travis-ci
  include:
  - name: Terminal Test
    script:
      - docker exec -it travis-cont /bin/sh -c "ifconfig; uname -a; docker ps -a; lsb_release -a"
  - name: App Test
    script:
      - docker exec -it travis-cont /bin/sh -c "./install-test.sh"
after_script:
  - docker exec -it travis-cont /bin/sh -c ""./userdata.sh"
#addons:
#  artifacts:
    # ...
#    paths:
#    - $(git ls-files -o | tr "\n" ":")
#    - $(ls /var/log/*.log | tr "\n" ":")
#    - $HOME/some/other/thing.log
#    - $(find sdk/test -name myriota_build.log | tr '\n' ':')
notifications:
  email:
    recipients:
    - vismid89@gmail.com
    on_pull_requests: false
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  slack:
    secure: eNX2TvooEww0VXGzl37bCukl/O2CQNS6Nk5kjxftaUigibFsDGR9bizPMmuBEHkSvwPcrrwT51x5/+rAdW1JR2U9megZViHHMlvJBJvMGL6BGZE53viyb4MSQ90/JGPn7tjGACUcdF0e1kpfysLMHy09isD+RZ7Cq1FHDDxZX8KL4OB/4P/rb0wos2FPlkImSHZbKaD3FiPI6sPaAS9tD4Y0nfNmQOJhTNuhrPxrR/HrQoPeDv17j/fgQUjGCwHy0KwVqu88SMHpCqboLcT1uxqlpHXf0a8EbEqU7cQyVLjhOZWZNsPR9JiSXWsD52jBDB8iIpDT3Ol2Qx/L3XbiSHr8ObCoglJKdppQbrCG3Gtiewo+SpfE9izqGVqKMku/3rXbMNQGdAOQmFSXvzjrrob4F1mkurbygQT+cvTKRmmnJ+mWe6kOP6wkj6vsGWDQ2/Hdpn1ayBX9BOOHWslk1oP4JHdHlE1xSqXhfn4zSs2HFZmdoHHLOi3TBuKFxIUi2WYxNgbuf12JD9UqTQYBui22y0DUzGEpwK8xUTDYf3xnOG8tJZie8Ug7Wvz0o8+MC2ehY7ZMi/u/bVoAs4qpy/GrsGS05s3NlSDbd0ervI220rPOTJbVUzHD9tAkgqxgd9Wb2SVzZP4k92gB93/S68J8mzc/EbMGNaIm+NNme60=
#    template:
#      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
