dist: trusty
sudo: required
services:
- docker
branches:
  only:
  - travis-ci
language:
- c
- python
before_install:
- chmod +x install-apt.sh
- tr -d '\r' < install-apt.sh > install-apt-r.sh
- chmod +x install-apt-r.sh
install: 
script:
- ifconfig
- cd blinky
- make
notifications:
  email:
    recipients:
    - vismid89@gmail.com
    on_pull_requests: false
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  slack:
    on_success: always
    rooms:
      - secure: "nPHKbExC1eYPFf+YZEJTUjxN7AhoCFogQgeHYv5N6jxA7jGtaXcVJ0pb+Sp+t8AGZSf49OXU6G7rt5SZJhIySquqdxD/z1h5b615OX+R4ALuWYoYKUyzpN+cJoGzlk9udbugiZznhVXCEbcJlwB4QONqgFu+AcWMIHUg1OdmnLJ/l3N5a6Ag/VOlpa07pFGM8cznSJJOCArQ+vRLVJs+SNcd13IrxeCBIlbOS2VLlsLJBya/egH8QnzNCnkEm+uJgDpL6ax1tQkhF12IO4icWOpMzNED7JvPJD+lrJFq9HpPyWAUwob8knjdyEC0yo3r00tq3WKjBIXwWbjmLp+gSaM2sNvCZVlShh3MCe+xtqKwhtpRxXshAaJKHT32hgNJcyI1lpgygMAubly/ii9S1qz5KTmPBOPmey3qWEoEExYtz3g5Jzqx5/xhzNJPCVL3NDI2VC+08SZ6BKahDphcvWbIzU+U274meenza9YdqeDy9BuU8sozVBLHcBDExaK7lfXrRHBxHuCaeVpOfY++VGLqACnnANIqcQQLQYMrHK/y/ykl1SO82RSiuUu4Unm0sUaXGxFG2Nl4l7CnYTzscCYo7ToeMtKmYwmaUmu48gIItdZAq5lED6J6pDWUzuaxXf4G52EClQc/61IsArWBsvt4oB9zB9WhKnd+AmSTRTQ="