dist: trusty
sudo: required
services:
- docker
branches:
  only:
  - travis-ci
language:
- c
- python
before_install:
# Docker image for ubuntu
- docker pull ubuntu:16.04
- docker build .
- chmod +x install-apt.sh
- tr -d '\r' < install-apt.sh > install-apt-r.sh
- chmod +x install-apt-r.sh
install: 
- sh install-apt.sh
script:
- ifconfig
- cd blinky
- make
notifications:
  email:
    recipients:
    - vismid89@gmail.com
    on_pull_requests: false
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  slack:
    secure: "HvMs6ftmgnxPWyZGM0wwlXc5gV3P0xEMs2HuoHR1d3FG3pNBn7/hwqdWz7rCUt4z1wGESABK5VMDMkk5UYN+PtsrqPv3x54wpj8G6h+P+cGHt5B3V/Zs12RU7/8sfH0W2oXgk30krq3RT1XodHqBxwzpqu6/2lsma0BZe1zAWIdMLDuN8+1rR2JEdMNl/mtQoBowC6q2YvK02XY3XrW5UB41m59wNXm8avx0FKi9RzClGUKXEil05brFr9kz4Ad2o3oJ0FR9wNQGq2hPM3WUsjv9MJ9HtVQlF3zbpSsHhIp7ko4S7NEuOkbj+SjGig6W+i7GbnSHd1lRKuqtqcaVgbBH7bk9dzzsKYLYfl5psX4PAS5boeNDvh5qAUNXvIRvARKpdTQzUohouNkjpM0hyCWYS2ORJV0/GYrQj5w/EI1org2F77+FJPphNzOoaw3QWoxq1fqowIg22pgiImH9gUoRWlz4o5IAoCXVUzlDVfOzdN5krKyDN0aWcZiRnmeNaccDY6dQ7Ia8JScvGJXSU0fRFrC2a5vOcqDeXCIqmm1C1MsvIcXn95R2J4FxxsIdbXksOqSJeAlIqAjNr0h9Yw1qhktKKVwDskBkLfkXFWv02DxKybq3opK1djJlzJQxrsskiCpSCnAJcE/j6F21n89VvdFLWZ1Aw2Krn9hIWkg="
    on_success: always