dist: trusty
sudo: required

services:
  - docker

#blocklist
branches:
  only:
    - travis-ci

language: 
  - c
  - python

install: 
  - ./install-apt.sh

script: 
  - ifconfig
  - scriptlog=$(mktemp)
  - exec > $scriptlog
  - exec 2>&1
  - cd blinky
  - make
  - cat $scriptlog 
#  - sudo python Health_Recorder.py

notifications:
 email:
  recipients:
    - vismid89@gmail.com
  on_pull_requests: false
  on_success: always
  on_failure: always
  on_start: always
  on_cancel: always
  on_error: always

    
