dist: trusty
sudo: required
services:
- docker
branches:
  only:
  - travis-ci
language:
- c
- python
before_install:
- chmod +x install-apt.sh
- tr -d '\r' < install-apt.sh > install-apt-r.sh
- chmod +x install-apt-r.sh
install:
#- sh install-apt-r.sh
script:
- ifconfig
- cd blinky
- make
notifications:
  email:
    recipients:
    - vismid89@gmail.com
    on_pull_requests: false
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  slack:
    secure: j98B+UnxJz72IV/3mUxqYrFQ9Hph/Lkof6gTajJ182pPIPKddfN2kgw/4o0gwFxLQ5lZ5H7J+6vjWSX/GDeryi8t8cXG6pRcVXImj9bx+cVhgVSW0jyw0ySLxyhOL9PjfD6uFlJlyPa5eQIMFwS0Q3GlRjlFh+KUVJ0LIs/3fLnxUX2JMVvFJEFbD90pVsAhrKsHKiGbdmjXUyY4rQmHsypAwQZSY+J0inIrWeXQKIkhcawX1sCpChOSgKJcw2gs79pFRCbU2+UHKTNi3rxSayVIbxq3U/0TSNQh3OVja/ATFtPisQLnAsEbnVP9P6eOIKetc9ve+HJqYxF/Bov4fe3BVgkrSIteBsQSykOsDTxULJMa1JM906dMehZBUv8L59i0aP2XdPZTb11U+72qYvRnqhSBqv7fTVj56T4lzOr2AzXt5xW5+YquhycuWQdIQ2Lq0tEdVn7jiYjUAsfzmpRIWmqIyUSfofTFMT/CPJc9Kw1cq59GXuD3TpqDlZklnaGwGFeF6djh5XOjwdJrDMeVTXRATw3Y4EIjDblTCnFZSteDmUQoWX/sP3pEjQdexerUXPYE2GQJ4j96CgnhVSRo3lUW5EHl6ASs/7Nb95wnq5l7Fq4uqGpwYuHf1c6OVOxtf5wtJ/dtz7p77EdseWyassCm/U3OQ6kNgsoJ6rk=
    on_success: change
    on_failure: always
    
