dist: trusty
sudo: required
services:
- docker
branches:
  only:
  - travis-ci
language:
- c
- python
before_install:
- chmod +x install-apt.sh
- tr -d '\r' < install-apt.sh > install-apt-r.sh
- chmod +x install-apt-r.sh
install: 
script:
- ifconfig
- cd blinky
- make
notifications:
  email:
    recipients:
    - vismid89@gmail.com
    on_pull_requests: false
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  slack:
    secure: jeb827XZraM9Pnx1HG/V2CGz4v0u5RDJQKXb7VBeOvJPVJ1Wys48kX1gtuSaNAzWsc0lRcggA+pRqCYfBk0xO4kRiXxWvKH4GFRtP+mvPUDYEYHTxi5w5rXCCsM+2FwFIKJ8QvrVHLfZ9YslZdZLGOz8aw4zNPn5bBFQ/upj2QihzovHbKwTb4fi3lY9Yv6De6jmDi4mNmeohPXGwNS2vFjIRHkHVUQwgogWK9NNjXDjkqaS4zRvH+mp02Fe2+E4XqLbak6S1XsaCBwuzW99dH0LL/OggNXF6ev4Vf1hC4oumzNQmaMsraG34HV//pf3pP/HXZirOOTRiRPlmk/QDqPn0P9kgp9c8x4VlSnGYadwXgoaryq3CCtVwz54rnyTjfsVnx4x9sTgOXGYbyqx2GiHpaH2zZvSFis+AQgK1X5beH1kHUFiZX9ho/fymG3dwMHsNuiwNQSJqo+XQAV4iUzxh93YboRYiKsF+S+fcrzm1hDGo4kt7OzAtoz4cr/2mmmcU1JHqjBrN0YrQE6v7NZ3WCkkv+UjD6cvEG2oEq6Hg25qWPg6gXfKwM5ZFiZmbfo51PBvk4pZDQdpc2E5Zsy5BHaVlT+0F6+rjQSHOkhaP0ITazNJMVTX38PJ5C/kcIapNNrxGWtDJ5B0I5vfYqAjPJF6T6Q/Uv5w8lQVjUw=
