dist: trusty
sudo: required
services:
- docker
language:
- c
- python

addons:
  apt:
    packages:
    - python-pip

before_install:
- python2 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'

script:
- testfolder=scripts
- echo "Test stage is Started"

stages:
  - name: build
  - name: test
    if: type IN (cron, push, pull_request)
  - name: testnextstage
    if: type IN (cron, push)

jobs:
  fast_finish: true
  allow_failures:
#  - stage: test
#  - testtype: test2
  include:
  - stage: build
    name: Build Ubuntu16.04
    env:
    - Build stage OS-Ubuntu16.04 Folder-Commslib
    script:
    - echo "Build stage for 16.04 is Complete"

  - stage: build
    name: mac os
    os: osx
    script:
    #- xcode-select --install
    #- brew install /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
    - sh install-mac.sh
    - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig

  - stage: test
    name: Test on Ubuntu16.04 satellite
    testtype: test1
    if: (NOT commit_message =~ /\[ci / OR commit_message =~ /\[ci satellite\]/)
    #if: commit_message =~ /(\[ci-one\]|\[ci-all\])/
    script:
    - echo "Test stage for 16.04 is Complete"

  - stage: test
    testtype: test2
    name: Test on Ubuntu16.04-dummy devops
    if: (NOT commit_message =~ /\[ci / OR commit_message =~ /\[ci devops\]/)
    script:
    - echo "Test stage for 16.04 devops is Complete"
    - bash -c "sleep 30; false"

  - stage: testnextstage
    name: Test on Ubuntu16.04 math
    testtype: prod
    if: NOT commit_message =~ /\[ci/ OR commit_message =~ /\[ci math\]/
    script:
    - echo "Test next stage stage for 16.04 is Complete"

notifications:
  email:
    recipients:
    - vismid89@gmail.com
    on_pull_requests: false
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
env:
  global:
  - testenv=vis
