name: test-pipe-fail

on: [push, pull_request]
    
jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        git clone -b vp-test1 https://github.com/Darleev/ManUProject.git
        cd ManUProject
        make -C runtest test_seed
