name: test-pipe-fail

on: [push, pull_request]
    
jobs:
  build:

    runs-on: self-hosted
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: make -C runtest test_seed

