name: test-pipe-fail

on: [push, pull_request]
    
jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: make -C runtest test_seed

